### ISSUE TITLE
Fix user validation

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#46]
Currently there's very little stopping users from abusing other users. Users can edit other users, signup using the same names and email, etc. To do:
- users should not be able to edit other users
- user emails should be unique
- user names should be unique
- must be logged in to edit your own profile

**Comment by TangoYankee** [comment]
There are logical checks to address a couple of these issues:
1. editing other users
  a. [users.py](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/views/users.py), line 23
2. unique user names
  b. [home.py](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/views/home.py), line 97

However, these logical checks do not prevent accessing the web pages directly.

**Comment by mosdevly** [comment]
Yeah I think i'd recently put that first change in, but theres a PR up that will make this even better.

I'll re-check the status of the unique email. I'd made a note some time ago but its possible that's also been addressed already.

**Comment by TangoYankee** [comment]
#### To-Do
- [x] users should not be able to edit other users
- [ ] user emails should be unique
- [x] user names should be unique
- [x] must be logged in to edit your own profile

**Comment by TangoYankee** [comment]
I'm closing this issue because the pressing issues have been addressed. I will open a low priority issue to prevent duplicate email addresses.
