### ISSUE TITLE
Django Transfer Checklist

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#74]
Currently Capabilities:
 - User
- [x] login/out
- [x] signup: username/optional email/password
- [x] edit
- [x] Join/Leave Cleanup

- Cleanup
- [x] View all 
- [x] View mine: Joined/Participated
- [x] View individual
- [ ] View on map
- [x] Create
- [x] Edit
- [x] Delete
- [x] Advertise on SCFix
- [x] Coordinate with Public Works
- [x] Manage preferred user and sql time formats

- Location
- [x] Lookup via address

- Errors
- [ ] Flash messages with failed actions: 
- [x] Login/Signup/Delete Profile 
- [x] Create/Edit/Delete Cleanup 

- Future
- [ ] Filter out old cleanups
- [ ] Transfer or delete cleanups of deleted users
- [ ] Track volunteer hours of users
- [ ] Create profile page with user notifications
- [ ] Link user with their adopt-a-spot page
- [ ] Lookup Location via cross-street

**Comment by mosdevly** [comment]
Good idea. :)

**Comment by mosdevly** [comment]
All code is transferred. We're back to knocking down the issues!
