### ISSUE TITLE
Dev Tools Checklist

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#81]
Our little wishlist of tools implement that will make maintenance much faster and easier for us!

- [x] Implement management command for populating the app with default data to make getting local setup.
- [x] Add fixtures for testing
- [x] Moar logs: Every view, utility, exception and helper method needs logs.
- [ ] Sphinx documentation
