### ISSUE TITLE
Views checklist

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#83]
Django Views: https://docs.djangoproject.com/en/1.11/topics/http/views/

Right now we have two categories of views: template views and api views.

The template views render our page templates. Api views are used for development, documentation and integrations. 

Todo:

- [x] Cleanup template views
- [x] Cleanup API views
- [x] Location API views
- [x] URL configuration
- [x] View tests: api and templates

**Comment by mosdevly** [comment]
Done in PR #89
